### ISSUE TITLE
napaka pri zamenjavi class-a vektorja

### ISSUE THREAD

**Issue by jernejbanevec** [jernejbanevec/APPR-2017#2]
Pozdravljeni, 
mislil sem da sem problem rešil, vendar mi ni dokončno uspelo, saj ko napišem "data$`ŠTEVILO SPLAVOV`<- as.numeric(data$`ŠTEVILO SPLAVOV`)" in data$`LETO`<- as.numeric(data$`LETO`) izgubim začetek številk. Kaj naj naredim?

**Comment by jernejbanevec** [comment]
Sem ugotovil da je dobro če najprej iz classa factor spremenim v character ter nato v numeric, tako da je issue brezpredmeten, saj bom jutri popravil še to napako. Hvala in lep pozdrav, Jernej

**Comment by jaanos** [comment]
Še bolje bo, če uporabiš funkcijo `parse_number` iz knjižnice `readr` - tako ne bo potrebna vmesna pretvorba.
