### ISSUE TITLE
delo od doma za repozitorij

### ISSUE THREAD

**Issue by jernejbanevec** [jernejbanevec/APPR-2017#4]
Pozdravljeni,
vedno ko poskušam doma narediti pull mi javi "ime imenika ni veljavno". Kaj sem naredil narobe?

**Comment by jaanos** [comment]
Na pamet težko rečem, bi pa najprej posumil, da imaš morda v poti do imenika s projektom kakšne presledke ali šumnike.

Če to ni problem, bi lahko malo podrobneje opisal napako - kdaj natanko se zgodi, morda kakšen posnetek zaslona (sliko lahko pripneš v issue enostavno tako, da jo potegneš v polje, kamor pišeš)?

**Comment by jernejbanevec** [comment]
Sem spremenil šumnike v poti do imenika s projektom in sedaj deluje, tako da grem sedaj popravljat ostale napake povezane z uvozom. Najlepša hvala in lep pozdrav.
